### ISSUE TITLE
ReferenceError: module is not defined

### ISSUE THREAD

**Issue by marcofranssen** [fregante/release-with-changelog#55] opened 2022-04-08 10:44 UTC
Action fails with following message.

```
Run fregante/release-with-changelog@v3.5.1
  with:
    token: ***
    draft: true
    exclude: ^Merge|^terraform-docs:
    prerelease: false
    commit-template: - {title} ({hash})
    template: ### Changelog
  
  {commits}
  
  {range}
  
    date-format: short
    sort: desc
    skip-on-empty: false
file:///home/runner/work/_actions/fregante/release-with-changelog/v3.5.1/distribution/index.js:1
module.exports =
^

ReferenceError: module is not defined
    at file:///home/runner/work/_actions/fregante/release-with-changelog/v3.5.1/distribution/index.js:1:1
    at ModuleJob.run (internal/modules/esm/module_job.js:145:37)
    at async Loader.import (internal/modules/esm/loader.js:18[2](https://github.com/my-org/my-repo/runs/5883732283?check_suite_focus=true#step:7:2):2[4](https://github.com/my-org/my-repo/runs/5883732283?check_suite_focus=true#step:7:4))
    at async Object.loadESM (internal/process/esm_loader.js:68:[5](https://github.com/my-org/my-repo/runs/5883732283?check_suite_focus=true#step:7:5))
```

**Comment by BelKed** [comment] 2022-04-08 11:56
This issue is duplicate of closed #54. Just quoting, what I have written in https://github.com/fregante/release-with-changelog/issues/54#issuecomment-1064049504:

> `v3.5.1` seems to point to https://github.com/fregante/release-with-changelog/commit/304ef3a41972f031ea67fa705ed37a811f37d1b1, which uses an incompatible Node version.
> This problem was fixed in the last commit (https://github.com/fregante/release-with-changelog/commit/9ebedfd0a59627582e5b5c711ee40355e1c43f38), which was not included in `v3.5.1` release.
>
> The `v3` tag points to a working version, so I recommend using an action like `fregante/release-with-changelog@v3`.

**Closed as completed** 2022-04-08 13:26 UTC
